home/urls.py
"""urls for the home app"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

school_application/urls.py
"""school_application URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('profiles/', include('profiles.urls')),
    path('students/', include('students.urls')),
    path('sales/', include('sales.urls')),
    path('lessons/', include('lessons.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'school_application.views.handler404'
handler500 = 'school_application.views.handler500'

students/urls.py
"""Urls for the students app."""
from django.urls import path
from .views import (
    StudentsView,
    StudentAddView,
    StudentView,
    StudentEditView,
    StudentDeleteView,
    )


urlpatterns = [
    path('students/', StudentsView.as_view(), name='students'),
    path('students/add/', StudentAddView.as_view(), name='student_add'),
    path('students/<int:pk>/', StudentView.as_view(), name='student_detail'),
    path(
        'students/<int:pk>/edit/',
        StudentEditView.as_view(),
        name='student_edit'
    ),
    path(
        'students/<int:pk>/delete/',
        StudentDeleteView.as_view(),
        name='student_delete'
    ),
]

students/models.py
"""Models for the students app."""
from django.db import models
from profiles.models import Parent
from sales.models import SalesManager


class Student(models.Model):
    """Student model"""
    first_name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    parent = models.ManyToManyField(Parent, related_name='child')
    birthday = models.DateField()
    address = models.CharField(max_length=100, blank=True, null=True)
    enrolled = models.DateTimeField(auto_now_add=True)
    classes_left = models.IntegerField(default=0, blank=True, null=True)
    sales_manager = models.ManyToManyField(
        SalesManager,
        related_name='student'
    )
    notes = models.TextField(blank=True)

    def has_classes_left(self):
        """Check if student has classes left"""
        return self.classes_left < 10

    def get_parents(self):
        """Get all parents of the student"""
        return self.parent.all()

    def get_sales_managers(self):
        """Get all sales managers of the student"""
        return self.sales_manager.all()

    def get_parent_usernames(self):
        """Get all parents of the student"""
        return [parent.user.username for parent in self.get_parents()]

    def __str__(self):
        """Return string representation of student."""
        return self.first_name + ' ' + self.last_name

    class Meta:
        """Meta class"""
        db_table = 'students'
        ordering = ['-enrolled']

students/forms.py
"""Forms for students app"""
from django import forms
from .models import Student


class AddStudentForm(forms.ModelForm):
    """Form for new student"""
    class Meta:
        """Meta class"""
        model = Student
        fields = [
            'first_name',
            'last_name',
            'parent',
            'birthday',
            'address',
            'classes_left',
            'sales_manager',
            'notes'
            ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'parent': forms.SelectMultiple(
                attrs={'class': 'form-control'}
                ),
            'birthday': forms.DateInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'classes_left': forms.NumberInput(attrs={'class': 'form-control'}),
            'sales_manager': forms.SelectMultiple(
                attrs={'class': 'form-control'}
                ),
            'notes': forms.Textarea(attrs={'class': 'form-control'})
        }

students/views.py
"""Views for the students app."""
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.views import View
from django.core.paginator import Paginator
from lessons.models import Lesson
from .models import Student
from .forms import AddStudentForm


class StudentAddView(View):
    """Student Add View"""
    def get(self, request):
        """Receive student add form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                form = AddStudentForm()
                return render(
                    request,
                    'students/student_add.html',
                    {'form': form}
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )

    def post(self, request):
        """Receive student add form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                form = AddStudentForm(request.POST)
                if form.is_valid():
                    print(form.cleaned_data)
                    student = form.save(commit=False)
                    sales_manager = form.cleaned_data['sales_manager'][0]
                    parent = form.cleaned_data['parent'][0]
                    student.save()
                    form.save_m2m()
                    student.sales_manager.add(sales_manager)
                    student.parent.add(parent)
                    student.save()
                    return HttpResponseRedirect(
                        reverse('students')
                    )
                return render(
                    request,
                    'students/student_add.html',
                    {'form': form}
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )


class StudentsView(View):
    """Students View"""
    def get(self, request, *args, **kwargs):
        """Receive students list"""
        if request.user.is_authenticated:
            if request.user.role == 4 or request.user.role == 5:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )
            else:
                p = Paginator(Student.objects.all(), 20)
                page = request.GET.get('page')
                students = p.get_page(page)
                students_number = Student.objects.all().count()
                context = {
                  'students': students,
                  'students_number': students_number
                }
                return render(
                    request,
                    'students/students.html',
                    context
                )

    def post(self, request, *args, **kwargs):
        """Receive students list"""
        if request.user.is_authenticated:
            if request.user.role == 4 or request.user.role == 5:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )
            else:
                classes = request.POST.get('classes')
                if classes == 'all':
                    p = Paginator(Student.objects.all(), 20)
                    page = request.GET.get('page')
                    students = p.get_page(page)
                else:
                    students_urgent = []
                    students = Student.objects.all()
                    for student in students:
                        if student.has_classes_left():
                            students_urgent.append(student)
                    p = Paginator(students_urgent, 20)
                    page = request.GET.get('page')
                    students = p.get_page(page)
                return render(
                    request,
                    'students/students.html',
                    {'students': students}
                )


class StudentView(View):
    """Student View"""
    def get(self, request, pk, *args, **kwargs):
        """Receive student detail"""
        if request.user.is_authenticated:
            if request.user.role == 5:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )
            else:
                student = get_object_or_404(Student, pk=pk)
                p = Paginator(
                    Lesson.objects.filter(students__in=[student]),
                    20
                )
                page = request.GET.get('page')
                lessons = p.get_page(page)
                return render(
                    request,
                    'students/student_detail.html',
                    {'student': student, 'lessons': lessons}
                )

    def post(self, request, pk, *args, **kwargs):
        """Receive student edit form"""
        if request.user.is_authenticated:
            if request.user.role == 5:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )
            else:
                student = get_object_or_404(Student, pk=pk)
                fromdate = request.POST.get('from_date')
                todate = request.POST.get('to_date')
                student = get_object_or_404(Student, pk=pk)
                lessons = Lesson.objects.filter(students__in=[student])
                p = Paginator(
                    lessons.filter(date__range=[fromdate, todate]),
                    20
                )
                page = request.GET.get('page')
                search_items = p.get_page(page)
                return render(
                    request,
                    'students/student_detail.html',
                    {'student': student, 'lessons': search_items}
                )


class StudentEditView(View):
    """Student Edit View"""
    def get(self, request, pk, *args, **kwargs):
        """Receive student edit form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                student = get_object_or_404(Student, pk=pk)
                form = AddStudentForm(instance=student)
                return render(
                    request,
                    'students/student_edit.html',
                    {'form': form, 'student': student}
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )

    def post(self, request, pk, *args, **kwargs):
        """Receive student edit form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                student = get_object_or_404(Student, pk=pk)
                form = AddStudentForm(request.POST, instance=student)
                if form.is_valid():
                    print(form.cleaned_data)
                    student = form.save(commit=False)
                    sales_manager = form.cleaned_data['sales_manager'][0]
                    parent = form.cleaned_data['parent'][0]
                    student.save()
                    form.save_m2m()
                    student.sales_manager.add(sales_manager)
                    student.parent.add(parent)
                    student.save()
                    return HttpResponseRedirect(
                        reverse('student_detail', args=[student.pk])
                        )
                return render(
                    request,
                    'students/student_edit.html',
                    {'form': form, 'student': student}
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )


class StudentDeleteView(View):
    """Student Delete View"""
    def get(self, request, pk, *args, **kwargs):
        """Receive student delete form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                student = get_object_or_404(Student, pk=pk)
                return render(
                    request,
                    'students/student_delete.html',
                    {'student': student}
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )

    def post(self, request, pk, *args, **kwargs):
        """Receive student delete form"""
        if request.user.is_authenticated:
            if request.user.role == 0 or request.user.role == 2:
                student = get_object_or_404(Student, pk=pk)
                student.delete()
                return HttpResponseRedirect(
                    reverse('students')
                )
            else:
                return render(
                    request,
                    'profiles/access_limitation.html'
                )

students/templates/students/student_add.html
{% extends "base.html" %}
{% load static %}

{% block extra_js %}
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      $('select').addClass('js-example-basic-single');

      $('.js-example-basic-single').select2({
        placeholder: 'Type name to search',
      });
      $('#div_id_assigned_to').css('width', '100%');
      $('.select2').css('width', '100%');
    });
    $(function () {
      $("#id_birthday").datepicker();
    });
  </script>
{% endblock%}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Students{% endblock %}

{% block content %}
  {% comment %} Add student page with limited access {% endcomment %}
  <div class="student">
    <div class="student__form--container">
      <h2 class="student__form--title">Add Student</h2>
      <form method="POST" class="student__form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="student__buttons">
          {% comment %} Go back to students page {% endcomment %}
          <a href="{% url 'students' %}" aria-label="Go to back to Student page"
            class="student__buttons--btn student__btn student__back--btn">
            <div class="student__btn--text">Cancel</div>
            <i class="far fa-window-close  student__btn--icon"></i>
          </a>
          {% comment %} Submit student changes button {% endcomment %}
          <button type="submit" class="student__buttons--btn student__btn student__confirm--btn">
            Save<i class="fas fa-save search__btn--icon"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

students/templates/students/student_delete.html
{% extends 'base.html' %}
{% load static %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Students{% endblock %}

{% block content %}
  {% comment %} Limit access to student deletion page {% endcomment %}
  <div class="student">
    <div class="student__form--container">
      <h2 class="student__form--title">Delete Student's data</h2>
      {% comment %} Delete student profile Form {% endcomment %}
      <form method="POST" class="student__form">
        {% csrf_token %}
        <div class="student__form--suggestions">
          <div>Are you sure you want to delete this student? </div>
          <div class="links">
            <a href="{% url 'student_detail' pk=student.pk %}" aria-label="Go Back to Student page"
              class="links__btn links__btn--content links__btn--name">
              <div class="student__btn--text">
                {{ student.first_name }} {{ student.last_name}}
              </div>
              <i class="fas fa-external-link-alt student__btn--icon"></i>
            </a>
          </div>
          <div>This student will permanently deleted from database.</div>
        </div>
        <div class="student__buttons">
          {% comment %} Go back to student profile page {% endcomment %}
          <a href="{% url 'student_detail' pk=student.pk %}" aria-label="Go Back to Student page"
            class="student__buttons--btn student__btn student__back--btn">
            <div class="student__btn--text">Cancel</div>
            <i class="far fa-window-close  student__btn--icon"></i>
          </a>
          {% comment %} Submit student changes button {% endcomment %}
          <button type="submit" class="student__buttons--btn student__btn student__confirm--btn">
            Delete<i class="fas fa-trash-alt search__btn--icon"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

students/templates/students/student_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_js %}
{% comment %} Datepicker implementation {% endcomment %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script>
  $(function () {
    $("#datepicker1").datepicker({
      dateFormat: 'yy-mm-dd',
    });
    $("#datepicker2").datepicker({
      dateFormat: 'yy-mm-dd',
    });
  });
</script>
{% endblock%}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Students{% endblock %}

{% block content %}
{% comment %} Access limitation for potentail clients and other parents {% endcomment %}
{% if request.user.role == 4 and request.user.username not in student.get_parent_usernames or request.user.role == 5 %}
<div class="access">
  <div class="access__error">

    <div class="access__error--image">
      <img src="{% static 'images/foxy_emoji.svg' %}" alt="Access error">
    </div>
    <p class="access__error--text">You are not authorized to view this page!</p>
    <div class="links">
      <a href="{% url 'user_profile' username=request.user %}" aria-label="Go to Your Profile page"
        class="links__btn links__btn--name links__btn--content">
        <div class="profile__btn--text">
          Back to your profile
        </div>
        <i class="fas fa-external-link-alt profile__btn--icon"></i>
      </a>
    </div>
  </div>
</div>
{% else %}
<div class="student">
  {% comment %} Rendering or deleting data if the user is Admin or Sales Manager {% endcomment %}
  {% if request.user.role == 0 or request.user.role == 2 %}
  <div class="student__edit">
    <a href="{% url 'student_edit' pk=student.pk %}" aria-label="Go to Edit Data Student page"
      class="student__btn student__edit--btn">
      <div class=" student__btn--text">Edit</div>
      <i class="fas fa-edit  student__btn--icon"></i>
    </a>
    <a href="{% url 'student_delete' pk=student.pk %}" aria-label="Go to Delete Student page"
      class="student__btn student__delete--btn">
      <div class="student__btn--text">Delete</div>
      <i class="fas fa-trash-alt student__btn--icon"></i>
    </a>
  </div>
  {% endif %}
  {% if request.user.username in student.get_parent_usernames %}
  <p class="student__message">Your child's profile</p>
  {% endif %}
  {% comment %} Student's Data {% endcomment %}
  <h2 class="student__title">{{ student.first_name|title }} {{ student.last_name|title }}</h2>
  <div class="profile__role">(Student)</div>
  <div class="student__info">
    <div class="student__data">
      <div class="student__data--heading">Full name:</div>
      <div class="student__data--info">
        {{ student.first_name|title }} {{ student.last_name|title }}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Birthday:</div>
      <div class="student__data--info">
        {{ student.birthday }}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Address:</div>
      <div class="student__data--info">
        {{ student.address|title }}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Parents:</div>
      <div class="student__data--info">
        {% for parent in student.get_parents %}
        <div class="links student__data--links">
          <a href="{% url 'user_profile' username=parent.user.username %}" aria-label="Go to Profile page"
            class="links__btn links__btn--name">
            <div class="student__btn--text">
              {{ parent|title }} ({{parent.get_relation }})
            </div>
            <i class="fas fa-external-link-alt student__btn--icon"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Notes:</div>
      <div class="student__data--info">
        {{ student.notes }}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Classes left:</div>
      <div class="student__data--info">
        {{ student.classes_left }}
      </div>
      <div class="student__label">
        {% if student.has_classes_left %}
        <a href="{% url 'sales_list' %}" aria-label="Go to Sales page" class="label__btn label__btn--name">
          <div class="student__btn--text">
            Urgent call
          </div>
          <i class="fas fa-exclamation-circle student__btn--icon"></i>
        </a>
        {% endif %}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Sales Managers:</div>
      <div class="student__data--info">
        {% for sales_manager in student.get_sales_managers %}
        <div class="links">
          <a href="{% url 'user_profile' username=sales_manager.user.username %}" aria-label="Go to User Profile page"
            class="links__btn links__btn--name">
            <div class="student__btn--text">
              {{ sales_manager|title }}
            </div>
            <i class="fas fa-external-link-alt student__btn--icon"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="student__data">
      <div class="student__data--heading">Enrolled date:</div>
      <div class="student__data--info">
        {{ student.enrolled|date:'m/d/Y' }}
      </div>
    </div>
  </div>
</div>
{% comment %} Student's Attendence data {% endcomment %}
<div class="classes">
  <h3 class="classes__title">Attendance:</h3>
  <form method="POST" class="classes__form">
    <h4 class="classes__form--heading">Search classes by date</h4>
    {% csrf_token %}
    <div class="classes__form--settings">
      <div class="datepicker__container">
        <div class="datepicker__container--title">From:</div>
        <input type="text" id="datepicker1" name="from_date" placeholder="mm-dd-yyyy">
      </div>
      <div class="datepicker__container">
        <div class="datepicker__container--title">To:</div>
        <input type="text" id="datepicker2" name="to_date" placeholder="mm-dd-yyyy">
      </div>
      <button type="submit" value="search" class="search__btn classes__form--btn">
        Search <i class="fas fa-search search__btn--icon"></i>
      </button>
    </div>
    <div class="classes__results">
      <div class="classes__results--summary">
        <strong>{{ lessons|length }}</strong> classes found
      </div>
      <div class="classes__results--container">
        {% for lesson in lessons %}
        <div class="classes__results--item">
          <a href="{% url 'lesson_detail' pk=lesson.pk %}" aria-label="Go to Lesson Detail page"
            class="links__btn links__btn--name links__btn--classes">
            <div class="profile__btn--text">
              <div>{{ lesson.date|date:'m/d/Y' }}</div>
              <div>{{ lesson.get_subject }}</div>
            </div>
            <i class="fas fa-external-link-alt profile__btn--icon"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </form>
  <div class="pagination">
    <div class="pagination__navigation">
      {% if lessons.has_previous and not lessons.has_next %}
      <a href="?page={{ lessons.previous_page_number }}" class="pagination__navigation--btn"
        aria-label="Go to previous page results">
        <i class="fas fa-chevron-left"></i>
      </a>
      <div class="pagination__navigation--fake">
        <i class="fas fa-chevron-right"></i>
      </div>
      {% elif lessons.has_next and not lessons.has_previous %}
      <div class="pagination__navigation--fake">
        <i class="fas fa-chevron-left"></i>
      </div>
      <a href="?page={{ lessons.next_page_number }}" class="pagination__navigation--btn"
        aria-label="Go to next page results">
        <i class="fas fa-chevron-right"></i>
      </a>
      {% elif lessons.has_next and lessons.has_previous %}
      <a href="?page={{ lessons.previous_page_number }}" class="pagination__navigation--btn"
        aria-label="Go to previous page results">
        <i class="fas fa-chevron-left"></i>
      </a>
      <a href="?page={{ lessons.next_page_number }}" class="pagination__navigation--btn"
        aria-label="Go to next page results">
        <i class="fas fa-chevron-right"></i>
      </a>
      {% else %}
      <div class="pagination__navigation--fake">
        <i class="fas fa-chevron-left"></i>
      </div>
      <div class="pagination__navigation--fake">
        <i class="fas fa-chevron-right"></i>
      </div>
      {% endif %}
    </div>
    <div class="pagination__location">
      Page {{ lessons.number }} of {{ lessons.paginator.num_pages }}
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

students/templates/students/student_edit.html
{% extends "base.html" %}
{% load static %}

{% block extra_js %}
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      $('select').addClass('js-example-basic-single');
      $('.js-example-basic-single').select2({
        placeholder: 'Type name to search',
      });
      $('#div_id_assigned_to').css('width', '100%');
      $('.select2').css('width', '100%');
    });
    $(function () {
      $("#id_birthday").datepicker();
    });
  </script>
{% endblock%}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Students{% endblock %}

{% block content %}
  {% comment %} Edit student profile with limited access {% endcomment %}
  <div class="student">
    <div class="student__form--container">
      <h2 class="student__form--title">Editing Student's data</h2>
      <form method="POST" class="student__form">
        {{ form|crispy }}
        {% csrf_token %}
        <div class="student__buttons">
          {% comment %} Go back to student profile page {% endcomment %}
          <a href="{% url 'student_detail' pk=student.pk %}" aria-label="Go Back to Student page"
            class="student__buttons--btn student__btn student__back--btn">
            <div class="student__btn--text">Cancel</div>
            <i class="far fa-window-close  student__btn--icon"></i>
          </a>
          {% comment %} Submit student changes button {% endcomment %}
          <button type="submit" class="student__buttons--btn student__btn student__confirm--btn">
            Save<i class="fas fa-save search__btn--icon"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}